fix(react-board): no consecutive create root calls
wixplosives/wcs-core pull request #675
Opened 2022-10-30 09:08 UTC by vlad-karnauch

2022-10-30 09:46 UTC, AviVahl commented on packages/react-board/src/react-error-handled-render.tsx
> +        this.props.onRender?.();
Could you explain why this is needed?

2022-10-30 09:46 UTC, AviVahl commented on packages/react-board/src/react-error-handled-render.tsx
> +let reactRoot: ReactDOMClient.Root | undefined = undefined;
Module state? What if I want to render two boards into two containers?
Is this the correct location to fix this?

2022-10-30 09:47 UTC, vlad-karnauch commented on packages/react-board/src/react-error-handled-render.tsx
> +        this.props.onRender?.();
when we rerender, I want the promise to resolve

2022-10-30 09:48 UTC, vlad-karnauch commented on packages/react-board/src/react-error-handled-render.tsx
> +let reactRoot: ReactDOMClient.Root | undefined = undefined;
what would you suggest?

2022-10-30 09:55 UTC, AviVahl commented on packages/react-board/src/react-error-handled-render.tsx
> +let reactRoot: ReactDOMClient.Root | undefined = undefined;
Hard to suggest without fully knowing the flow that caused the warning.

My guess is that the place that calls board's render from our code has state and should handle consecutive rerenders of a (pseudo hot reloaded) board into the same container.

2022-10-30 10:37 UTC, vlad-karnauch commented on packages/react-board/src/react-error-handled-render.tsx
> +let reactRoot: ReactDOMClient.Root | undefined = undefined;
I'm also adding a separate PR to handle it there. 
In addition, this function should be able to handle such cases.
You are right about the module state; let me see what I can do.

2022-10-30 13:31 UTC, AviVahl requested changes

2022-10-30 13:31 UTC, AviVahl commented on packages/react-board/src/react-error-handled-render.tsx
> +const reactRootByContainer = new Map<HTMLElement, ReactDOMClient.Root>();
weakmap

2022-11-03 11:06 UTC, AviVahl commented on packages/react-board/test/create-board.spec.tsx
> +        await board.render(canvas);
we usually do wrap such checks with an expect, so the error message will be clear upon rejection. Meaning it would say something like "expected something not to reject, but it rejected with error 456" rather than just "error 456".

we've used `chai-as-promised` in other libraries, but it really leaves a lot to be desired.
I'll leave it up to you to decide whether it's worth it in this case or not.

2022-11-03 11:06 UTC, AviVahl commented on packages/board-plugins/test/css-vars-plugin.spec.ts
> +        cleanupAfterTest.add(cleanupRender);
nice catch.

2022-11-03 11:06 UTC, AviVahl approved these changes

2022-11-07 10:25 UTC, merged